#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

(
cd image

javac -cp "/home/yagmur/ij153-linux64-java8/ImageJ/ij.jar" -d . TwoPhaseCapture.java


java  -cp "/home/yagmur/ij153-linux64-java8/ImageJ/ij.jar": capture.TwoPhaseInterface.TwoPhaseCapture
)

